version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - 2224:2224
      - 8008:8008
    networks:
      - swarm-network
    volumes:
      - GITLAB_HOME_data:/var/opt/gitlab
      - GITLAB_HOME_logs:/var/log/gitlab
      - GITLAB_HOME_config:/etc/gitlab
    # shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
      GITLAB_OMNIBUS_CONFIG: "gitlab_rails['gitlab_shell_ssh_port'] = 2224"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 4

configs:
  gitlab:
    file: ./gitlab.rb

secrets:
  gitlab_root_password:
    file: ./root_password.txt

volumes:
  GITLAB_HOME_data:
    driver: local
    #driver_opts:
    #  type: nfs
    #  o: nfsvers=4.1,addr=anqci.file.core.windows.net,nolock,soft,rw
    #  device: :/anqci/dev-storage/gitlab/data
  GITLAB_HOME_logs:
    driver: local
    #driver_opts:
    #  type: nfs
    #  o: nfsvers=4.1,addr=anqci.file.core.windows.net,nolock,soft,rw
    #  device: :/anqci/dev-storage/gitlab/logs
  GITLAB_HOME_config:
    driver: local
    #driver_opts:
    #  type: nfs
    #  o: nfsvers=4.1,addr=anqci.file.core.windows.net,nolock,soft,rw
    #  device: :/anqci/dev-storage/gitlab/config

networks:
  swarm-network:
    external: true
  
